### ISSUE TITLE
Reasons I prefer xUnit over MSTest and NUnit

### ISSUE THREAD

**Issue by SeanKilleen** [SeanKilleen/seankilleen.github.io#119]
# Reasons I prefer xUnit over MSTest:

* `Fact` and `Theory` (easily parameterized tests)
 * Forces you to distinguish between a test that can never fail and a test that might fail because of what you're passing it.
* No setup / teardown
* Attributes (that are extensible)
* `Assert.Throws<T>`
* `xunit.runner.visualstudio` package means you don't need an extension to run the tests
* With `FluentAssertions` library, can do the following (note may be possible inside of MSTest too):
```
Action act = () => myClass.DoAThingThatBlowsUp();
act.ShouldThrow<ArgumentNullException>().And.ParamName.Should().Be("myParam");
```

Add your own below via comments and I'll turn it into a blog post and give you credit!

**Comment by SeanKilleen** [comment]
via Chris Missal: MS doesn't actually use MSTest -- they use xUnit on asp.net 

https://github.com/aspnet

**Comment by SeanKilleen** [comment]
Some helpful (older) articles:

* ["Why MSTest is the IE6 of test frameworks" (Osherove)](http://osherove.com/blog/2011/8/24/why-mstest-is-the-ie6-of-unit-test-frameworks.html)
* ["Why I'm migrating from MSTest to xUnit" (Seemann)](http://blog.ploeh.dk/2010/04/26/WhyImmigratingfromMSTesttoxUnit.net/)

**Comment by SeanKilleen** [comment]
Also, MSTest is slow -- good point: https://twitter.com/mistersql/status/608724039545270273

**Comment by SeanKilleen** [comment]
But in general, Concepts > Frameworks: 

https://twitter.com/scichelli/status/608724981015379968

**Comment by bradwilson** [comment]
Microsoft uses [xUnit.net](https://github.com/xunit/xunit) for a lot more than just ASP.NET: All of the open sourced projects (including the CLR and the Roslyn compiler) are using it.

https://github.com/dotnet/corefx/blob/4e0b645e4312b784bc6e9c1a76d9fec58d220380/src/System.Linq/tests/ToArrayTests.cs#L8
https://github.com/dotnet/roslyn/blob/e0371c92cf8e2c0b0390d848405b605f872dab70/src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs#L11

**Comment by SeanKilleen** [comment]
Also noted on Twitter (todo: link) that MSTest has no console-level runner. This makes it really hard to run in any other build system besides TFS.
