### ISSUE TITLE
Header Line-heights are very tight

### ISSUE THREAD

**Issue by RyKilleen** [SeanKilleen/seankilleen.github.io#132]
Possibly they were set for a different font? Will submit pull request, seemingly affects h1s / h2s most.

**Comment by SeanKilleen** [comment]
@RyKilleen i think the theme is doing something strange where the heights are proportionally calculated. Feel free to change any of that though.

**Comment by RyKilleen** [comment]
This happens in the[ mixin file ](https://github.com/SeanKilleen/seankilleen.github.io/blob/8fae9c69e616f05064a868540e0d461e29db693b/_sass/mixins.scss#L45)

I recommend over-riding after the mixin is used, in the[ typography file. ](https://github.com/SeanKilleen/seankilleen.github.io/blob/8fae9c69e616f05064a868540e0d461e29db693b/_sass/typography.scss#L6)

My guess is there was a font-face change, and the typography calcs could be tweaked. For now though, the H1s are the only offenders. Setting the line-height back to 1 looks fine.

**Comment by SeanKilleen** [comment]
Closing this as the headers / lines should be waaay better now that I've adopted the latest rendition of the theme.
