### ISSUE TITLE
Getting MiniProfiler to work with pure AngularJS + WebAPI

### ISSUE THREAD

**Issue by SeanKilleen** [SeanKilleen/seankilleen.github.io#199]
In conjunction with http://stackoverflow.com/questions/38249465/miniprofiler-how-do-i-profile-an-angularjs-webapi-app

Man, that was a buuuunch of pain.
- Adding the MiniProfiler and MiniProfiler.EF6 packages
- Move MiniProfiler to use SQL of some kind (might not be necessary?)
  - With a migration
- Separate CORS access on the miniprofiler path
- Pulling in the client-side files
- Setting up the script tag
- Exposing the `X-MiniProfiler-Ids` header via a filter and adding it.
- Setting it up on Start
- Adding begin/end request logic
- Add the jQuery template files to the index page
- Fix for displaying the templates (?)
# Helpful Snippets
#### Creating the filter

```
public class AddMiniProfilerCORSHeaderFilter : ActionFilterAttribute
    {
        public override void OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
        {
            actionExecutedContext.Response.Headers.Add("Access-Control-Expose-Headers", "X-MiniProfiler-Ids");
        }
    }
```
#### Adding the filter during bootstrapper

`config.Filters.Add(new AddMiniProfilerCORSHeaderFilter());`
#### Change to SQL Storage in Startup

```
           var connectionString = ConfigurationReader.GetConnectionString(Constants.ConfigSettings.CONNECTION_STRING_NAME);

            //This assumes DB migration has been run that adds the MiniProfiler tables.
            MiniProfiler.Settings.Storage = new SqlServerStorage(connectionString);
            MiniProfilerEF6.Initialize();
```
#### Begin/End Request

```
       protected void Application_BeginRequest()
        {
            if (Request.IsLocal || ConfigurationReader.GetAppSetting(Constants.ConfigSettings.USE_PROFILER, false))
            {
                var sessionId = Guid.NewGuid().ToString();
                MiniProfiler.Start(sessionId);
            }
        }

        protected void Application_EndRequest()
        {
            MiniProfiler.Stop();
          }               
```
#### Extra IIS Stuff for Path

```
  <location path="mini-profiler-resources">
    <system.webServer>
      <httpProtocol>
        <customHeaders>
          <add name="Access-Control-Allow-Origin" value="https://localhost:5000" />
          <add name="Access-Control-Allow-Methods" value="GET,POST,PUT,HEAD,DELETE,OPTIONS" />
          <add name="Access-Control-Allow-Headers" value="*" />
        </customHeaders>
      </httpProtocol>
    </system.webServer>
  </location>
```
#### Migration

(has to add the MiniProfiler package to the project for the script)

```
   public partial class MiniProfilerTables : DbMigration
    {
        readonly List<string> _miniProfilerTableNames = new List<string>
        {
            "miniprofilerclienttimings",
            "miniprofilertimings",
            "miniprofilers"
        };

        public override void Up()
        {
            Sql(SqlServerStorage.TableCreationScript);
        }

        public override void Down()
        {
            foreach (var table in _miniProfilerTableNames)
            {
                DropTable(table);
            }
        }
    }
```

**Comment by SeanKilleen** [comment]
PR for reference: https://github.com/NCARB/e-portfolio/pull/401

**Comment by cottsak** [comment]
@SeanKilleen Is there a complete diff somewhere I can use to get all the miniprofiler/angular bits in one place? Advice on the internets seems very fragmented.

**Comment by SeanKilleen** [comment]
@cottsak unfortunately I've moved on to a different project before I could get this fully working and in place. However, I think I'm about to have another shot on a different project. :) 

See [this StackOverflow thread](http://stackoverflow.com/questions/38249465/miniprofiler-how-do-i-profile-an-angularjs-webapi-app) for some more insight from others.

If I do manage to get it all set up, I'll 100% be blogging about it because I completely agree that advice is fragmented. 

And if you happen to get there first, I'd love to collaborate with you on a post or cite yours, so keep me posted. thanks!

**Comment by cottsak** [comment]
Thanks mate. My environment is slightly different to the one you mentioon in that SO question.

I'm using OWIN and so far have:
```
            MiniProfilerEF6.Initialize();
            app.Use((context, next) =>
            {
                MiniProfiler.Start();

                return next.Invoke();
            });
```
That's the best I could think of so far as a substutite for `Application_BeginRequest`.

A few questions:

* Do I still need the `Access-Control-Expose-Headers` header?
* Do I still need to find out some way to `MiniProfiler.Stop();`?
* Do we really need the Handler? (`<add name="MiniProfiler" path="mini-profiler-resources/*" ..`) It seems so antiquated.

I'll go and add the CSS `<link rel="stylesheet" href="js/lib/miniprofiler/includes.css" />`

But which js block do I need?
This one?
```
  <script async type="text/javascript" 
    id="mini-profiler" 
    src="js/lib/miniprofiler/includes.js?v=1.0.0.0" 
    data-current-id="" 
    data-path="https://localhost:44378/api/profiler/" 
    data-children="true" 
    data-ids="" 
    data-version="1.0.0.0" 
    data-controls="true" 
    data-start-hidden="false" 
    data-trivial-milliseconds="5">
  </script>
```

Or the one from @yellis?
```
<script async type="text/javascript" id="mini-profiler" 
        src="{path}includes.js?v={version}" data-version="{version}" 
        data-path="{path}" data-current-id="{currentId}" 
        data-ids="{ids}" data-position="{position}" 
        data-trivial="{showTrivial}" data-children="{showChildren}" 
        data-max-traces="{maxTracesToShow}" data-controls="{showControls}"
        data-authorized="{authorized}" data-toggle-shortcut="{toggleShortcut}" 
        data-start-hidden="{startHidden}" data-trivial-milliseconds="{trivialMilliseconds}">
</script>
```

**Comment by cottsak** [comment]
I'm closer:

* I needed the `AddMiniProfilerCORSHeaderFilter`
* I got the css in (not returning 404 in browser) `<link rel="stylesheet" href="lib/miniprofiler/includes.css" />`
* JS seems to be working with:
```
    <script async type="text/javascript"
            id="mini-profiler"
            src="lib/miniprofiler/includes.js?v=1.0.0.0"
            data-current-id=""
            data-path="https://localhost:44398/api/profiler/"
            data-children="true"
            data-ids=""
            data-version="1.0.0.0"
            data-controls="true"
            data-start-hidden="false"
            data-trivial-milliseconds="5">
    </script>
```
* And I think the profiling is working now. Requests are returning the IDs in the header ``:
```
            MiniProfilerEF6.Initialize();
            app.Use(async (context, next) =>
            {
                // begin request?
                MiniProfiler.Start();

                await next.Invoke();

                // end request?
                MiniProfiler.Stop();
            });
```

My issue now seems to be CORS related. I'm getting this in Chrome console:
```
XMLHttpRequest cannot load https://localhost:44398/api/profiler/results. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.
```

So I'm not sure how the `/api/profiler/results` endpoint is supposed to be served? What sets that up and how is it routed? I'm wondering since I'm not using MVC (only webapi via Owin) that maybe the routing is failing? Ideas?

Help me Obiwan @NickCraver, you're my only hope!

**Comment by SeanKilleen** [comment]
@cottsak Hi Matt,

This is my own personal repo for blog posts drafts that I haven't yet written. 

While I understand where you're coming from, I don't think that I want it to be a place where we work through this issue, and I don't think I want to ping folks who are already working on important solutions to come work through an issue in the space of my blog post draft. It doesn't seem like the right forum.

It may make sense for you to post something over on the [MiniProfiler Github repo](https://github.com/MiniProfiler/dotnet), where a larger community could be available to work through things with you.

I appreciate the spirit of you picking things up, and I'm glad you found this repo, but it doesn't seem fit for purpose and I don't want to drag others into this space.

**Comment by cottsak** [comment]
@SeanKilleen Totally understand and agree. Will move and delete
