### ISSUE TITLE
Added Last Edited date under title post

### ISSUE THREAD

**Issue by RyKilleen** [SeanKilleen/seankilleen.github.io#224]
Considered a standard for blogs / news, expected location by users. Second most relevant piece of info on the page

**Comment by SeanKilleen** [comment]
I don't know that I actually have this information. Because it's a static site, any changes I make are automatically re-published.

**Comment by RyKilleen** [comment]
<time datetime="{{ page.date | date_to_xmlschema }}">{{ page.date | date: "%B %d, %Y" }}</time> You're already using it in the page layout.

**Comment by SeanKilleen** [comment]
Ah, I see. So this issue is a duplicate of #220?

**Comment by RyKilleen** [comment]
Yerp
