### ISSUE TITLE
Access Token Scope for GitHub Pages build

### ISSUE THREAD

**Issue by GuruCharan94** [SeanKilleen/seankilleen.github.io#452]
I was reading [this blog post](https://seankilleen.com/2020/02/how-to-deploy-github-pages-on-a-schedule-to-publish-future-posts/) and was wondering what should be the scope of the token.

**Comment by SeanKilleen** [comment]
@GuruCharan94 that's a great question; thanks for asking it. 

I'm not entirely sure what the minimum scope needs to be, and I'll try to update the blog post once I find out that information.

The access key that I'm currently using is scoped to:

* repo:status
* repo_deployment
* public_repo
* admin:repo_hook
* read:user
* user:email
* user:follow
* workflow

Some of that I know is extraneous (e.g. user:follow) -- I can update the scopes and see what the minimum is that I can get away with. Luckily, you can update the scopes for the token after it's created.

**Comment by GuruCharan94** [comment]
That was quick ! Great, thanks :)

**Comment by GuruCharan94** [comment]
I have my token scoped to `public_repo` and it works fine.

**Comment by SeanKilleen** [comment]
That's super helpful, thank you! I was just thinking tonight that I needed
to try that out but the baby had other plans. 😆

Thanks for sharing; I'll update the post. Do you have a GitHub username or
Twitter account I can share in the article to say thanks?

**Comment by GuruCharan94** [comment]
Baby gonna baby 😂😂.. I go by @ gurucharan94 on both Twitter and GitHub.
