### ISSUE TITLE
Move away from Disqus

### ISSUE THREAD

**Issue by SeanKilleen** [SeanKilleen/seankilleen.github.io#577]
Disqus is showing Taboola ads. I don't like that, and I never authorized it. No idea how long it's been going on. So I'm likely going to move away from the platform.

## Steps

* [x] Disable comments on all posts that have none (#578)
* [ ] Get Giscus added to Minimal Mistakes: https://github.com/mmistakes/minimal-mistakes/pull/3022
* [ ] Create discussions and migrate comments from Disqus
* [ ] Switch theme to use giscus
* [ ] Re-enable comments on all posts

Will require GitHub accounts for discussions, but given that it's free I feel OK about it, and I'll provide other avenues of contact.

**Comment by ljvmiranda921** [comment]
Hi @SeanKilleen , found your blog when I'm doing scheduled builds for github. Looked at your Issues and saw a familiar pain point. 

I solved this by using [utterances](https://utteranc.es/): https://ljvmiranda921.github.io/notebook/2021/03/26/migrating-from-disqus-to-utterances/

Another option is this, if you prefer Github Discussions: https://github.com/laymonage/giscus

**Comment by SeanKilleen** [comment]
@ljvmiranda921 Hi and *thank you*! Super awesome of you to drop these links there. I'll definitely be checking them out.

**Comment by SeanKilleen** [comment]
@ljvmiranda921 giscus looks like exactly what I'm looking for. This is hugely helpful. Again, thanks!

**Comment by SeanKilleen** [comment]
Inspired by @ljvmiranda921, I'm currently adding giscus support to MinimalMistakes so I can enable it at the theme level: https://github.com/mmistakes/minimal-mistakes/pull/3022

**Comment by ljvmiranda921** [comment]
Hey @SeanKilleen , glad to be of help!

**Comment by SeanKilleen** [comment]
Closed via #651.
