### ISSUE TITLE
Shifting meetings to the left

### ISSUE THREAD

**Issue by SeanKilleen** [SeanKilleen/seankilleen.github.io#686]
I've seen a lot of meetings go sideways. And with the surge of remote work the past year and a half, we've seen a dramatic increase in remote work and the communication challenges that can go along with it, especially for organizations that aren't adapting to current circumstances.

Dear reader, I'd love to save you that trouble.

## What Do We Mean by "Shift to the Left" here? 

In software development, feedback loops are key. If we can iterate 10 times on something while our competitors are still getting their shoes on, chances are we're going to come out ahead. This ability to adapt and respond to change is one of the driving forces at the heart of Agile software development. 

If we visualize a process as a series of columns from left to right, such as in Kanban, then "shifting to the left" means avoiding issues earlier in the process. For example, if we have a "QA step" and bugs are often found there, could we shift the process to the left by automating tests earlier on to make QA go more smoothly? If a work item gets to a sign-off phase and there are issues, could we work to understand things better up front to avoid that hiccup and achieve a state of flow? 

## Meetings are another form of feedback loop. 

They involve scheduling and logistical acrobatics, they steal focus, they cost a lot of money, and they often lead to more meetings. What can we do to get ahead of these expensive feedback loops, or at least make them smaller? 

## The Best Meeting is No Meeting at All

Meetings should be a value stream. What is the outcome of a meeting? Surely we can get to that outcome faster.

| If your meeting is to... | ..then try this instead | 
| ---------------------- | ---------------- |
| Make an announcement | E-mail, Organization Chat e.g. Slack or Teams |
| Get Feedback | Set up a form and send via e-mail, take a poll in Slack or similar |
| Get consensus |  | 
| Reach people who don't read your e-mails | Accept that those people might be too busy or too disinterested. Maybe they don't need to be involved. If you have a decision to make, make it without them. | 
| Present an award | Private congratulation and a public e-mail announcement? Make a part of another meeting? (NOTE: awards in meetings can be very nice; just do it consciously.) |
| Brainstorm | A meeting might be helpful for this. But ensure you facilitate, do the prep work, and block off time |

## Shift accountability to the left by making a decision first

I got this one from Al Pitampalli's (TODO: Spelling) great book, "Read this before our next meeting." (TODO: Link)

How can we make a decision if we're not doing it as a group in meetings? 

* Find who the accountable person is and get them to make a decision instead. 
* If you're not sure, ask the group to make someone accountable and volunteer for someone to choose you. 
* Did nobody volunteer? Congrats, you're it! Make the decision or drop it.

## Shift attendance to the left with an actual agenda

Ever been in a meeting where you or others realized you weren't really needed halfway through? Painful, right? 

Every meeting invite should contain:

* A clear goal / expected outcome of the meeting
* An idea of why an invitee is invited to the meeting, down to the individual level if possible.
* Exactly what discussion points you intend to cover

Beyond just listing those items, you have to ensure that you actually stick to it, so if the discussion deviates, others who have opted out (more on this later) will have a chance to duck back.

## Shift noise to the left by encouraging opt-out

Sometimes when you invite people to a meeting, they feel that they _have_ to attend. This leads to a lot of wasted time. 

State in your meeting invite that it's OK to opt-out -- but also that the work of the meeting will go forward without the attendees who aren't present. If someone really does feel they're critical but has a conflict, they can ask for a re-schedule (or better yet -- delegate their proxy to someone else).

## Shift focus to the left by respecting time boundaries

* Your meetings should start on time. I usually allow two-minute buffer max for technical issues. If someone is late, they should be able to catch up on the notes.
* Your meetings should end 5 minutes early. Do not be the person who causes someone to be late to their next meeting if you can ever help it. The extra 5 min don't make a difference.
* Aim to accomplish the purpose of the meeting and end there. Did the meeting run over for some reason or things go off the rails? This is your opportunity to revisit either your planning for the agenda or your facilitation skills.

## Shift questions to the left with prep

* Add context, background, notes on prior discussions, things that have been tried etc. to the meeting invite. Don't let the invite just be an empty space.
* Indicate that you expect people to actually read this prep if they're going to attend the meeting.
* Refuse to recap for anyone or go over the points. Assume people read it.

## Shift ambiguity to the left by capturing notes and actions

* Take notes, or ask someone you trust (and who can type quickly) to take notes. Taking notes is also a great way to remain in a facilitator role rather than taking all the air out of the room while leading the meeting. Don't forego this because you can't type fast. If you're taking meetings and you type slow, cut the scope of the meeting.
* Your notes should start out with a section for "next actions". Names and rough dates should go next to any item entered there.
* Capture as much as possible, including any additional decisions made and any additional context needed.
* If possible, capture the notes on a screen everyone can see. Encourage people to correct the notes if they seem unclear or incorrect.
* Send the notes out before the end of the meeting. I usually do this as a reply-all to the invite so that people who choose to opt out are still informed, which encourages them to not waste time attending if they don't need to.

## A great book for reference

I read this book years ago, but it stuck with me. While the exact text has faded from my memory, I know there's a good deal of overlap with and inspiration taken from this book.

TODO: Reference "read this before our next meeting", note that you probably internalized several tips from it.

**Comment by W0GER** [comment]
Great article! 

The company I work for is 100% work from home. We have an office, but going "in" to the office is voluntary, which I like. A lot of the points you make here are really key for online meetings as well as in-person meetings. 

As I read your thoughts here, I thought about my calendar. I think you're missing one category of meetings - scrum ceremonies. Here's how we've moved those to the "left": 

We have a "Joint Planning Session" which all 6 of our scrum teams attend, we use this for announcements, review of team metrics, review of product metrics, awards, light training, and review what the Product Owners have as their top backlog items. We do the last item looking for any cross team dependencies that may exist; then the larger team break into their scrum teams for traditional sprint planning. 

Our sprint review is also a combination of all 6 sprint teams and works as a presentation to our stakeholders. This single meeting better for our stakeholders (instead of 6 separate meetings). If there are technical topics we want to share across the teams, those topics are moved to either the Joint Planning Session or a separate training session. 

Our product owners have moved our sprint grooming sessions to the left by including the list of stories (with links) to groom. This allows are developers to do research and be ready to discuss the stories. 

Thanks for sharing your thoughts!
Roger
